version: 2

registries:
  github-navikt:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}

updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - github-navikt
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore
      include: scope
