#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# Credentials fra denne appen roteres årlig.
# Ved rotasjon (neste: ca. desember 2026), kjør:
#   just dump-credentials
# og oppdater secreten "nks-bob-frontend-lokal-credentials" i NAIS Console (dev-miljø)
# med de nye verdiene. Kjør deretter 'just setup' på nytt.
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .nais/azure-ad-app-lokal.yaml
#
# Se hva som ligger deployet:
# kubectl apply view-last-applied AzureAdApplication nks-bob-frontend-lokal
#
# skamløst kopiert fra familie-tilbake-frontend
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: nks-bob-frontend-lokal
  namespace: nks-aiautomatisering
  labels:
    team: nks-aiautomatisering
spec:
  logoutUrl: "http://localhost:4000"
  tenant: nav.no
  # enabled: true
  # allowAllUsers: false
  claims:
    groups:
      - id: "dcb5ec4c-8027-428c-9dfd-15852388001c" # Administratorgruppe
      - id: "1a7b1fec-44c3-40c1-bf1d-f462b5a90a26" # Brukergruppe
  replyUrls:
    - url: "http://localhost:4000/oauth2/callback"
  secretName: azuread-nks-bob-frontend-lokal
