apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nks-bob-frontend
  namespace: nks-aiautomatisering
  labels:
    team: nks-aiautomatisering
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{{image}}}
  port: 3030
  ingresses:
    - https://bob.ansatt.dev.nav.no
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    min: 1
    max: 2
  azure:
    application:
      tenant: nav.no
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "dcb5ec4c-8027-428c-9dfd-15852388001c" # Administratorgruppe
          - id: "1a7b1fec-44c3-40c1-bf1d-f462b5a90a26" # Brukergruppe
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: nks-bob-api
  env:
    - name: LOGIN_URL
      value: https://bob.ansatt.dev.nav.no/oauth2/login
    - name: GIT_COMMIT
      value: {{{commit}}}
    - name: MILJO
      value: dev
    - name: SALESFORCE_DOMAINS
      value: https://app-connect-7729.scratch.my.salesforce-setup.com
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
