export const ABBREVIATIONS: Record<string, string> = {
  aap: "arbeidsavklaringspenger",
  aapen: "work assessment allowance",
  aapnn: "arbeidsavklaringspengar",
  aareg: "arbeidsgiver- og arbeidstakerregisteret",
  abs: "avdelingen som behandler saken din",
  aev: "arbeidsevnevurdering",
  afpo: "AFP offentlig",
  afpp: "AFP privat",
  ag: "arbeidsgiver",
  agp: "arbeidsgiverperiode",
  akt: "aktivitetsplan",
  ang: "angående",
  ap: "alderspensjon",
  apf: "alderspensjon fra Folketrygden",
  apgj: "alderspensjon med gjenlevenderett",
  arbt: "arbeidstaker",
  baor: "ordinær barnetrygd",
  bap: "barnepensjon",
  baut: "utvidet barnetrygd",
  bb: "barnebidrag",
  bbo: "barnebidrag over 18 år",
  behe: "behandlende enhet",
  bf: "bidragsforskudd",
  bg: "bidragsgjeld",
  bhg: "barnehage",
  bm: "bidragsmottaker",
  bp: "bidragspliktig",
  bt: "barnetrygd",
  bten: "child benefit",
  bti: "barnetillegg",
  bts: "barnetilsyn",
  bv: "barnevernet",
  dinp: "Din pensjon",
  dins: "din side på nav.no",
  dok: "dokumentasjon",
  dp: "dagpenger",
  dpen: "unemployment benefits",
  dpv: "dagpengevedtak",
  dvs: "det vil si",
  eb: "etterbetaling",
  ees: "egenerklæringsskjema",
  eeu: "egenerklæring for utenlandsk sykemelding",
  eeuen: "personal decleration for foreign sick leave",
  ef: "enslig forsørger",
  efy: "enslig forsørger ytelser",
  eo: "etteroppgjør",
  epf: "enkeltpersonforetak",
  es: "engangsstønad",
  famk: "familievernkontoret",
  fb: "ferdigbehandlet",
  feks: "for eksempel",
  fep: "feriepenger",
  ffd: "første fraværsdag",
  fnr: "fødselsnummer",
  foafp: "Fellesordningen for AFP",
  fom: "fra og med",
  fp: "foreldrepenger",
  fpen: "parental benefits",
  fpma: "foreldrepenger med aktivitetskrav",
  fpp: "foreldrepengeperiode",
  fpua: "foreldrepenger uten aktivitetskrav",
  freg: "folkeregisteret",
  fta: "friskmelding til arbeidsformidling",
  ftr: "Folketrygden",
  fu: "feilutbetaling",
  gar: "garantipensjon",
  gb: "grunnbeløpet",
  ghs: "grunn- og hjelpestønad",
  gjp: "gjenlevendepensjon",
  gjy: "gjenlevendeytelser",
  gs: "grunnstønad",
  hfd: "Ønsker deg en fin dag.",
  hfden: "Wish you a nice day.",
  hk: "honnørkort",
  hms: "Hjelpemiddelsentralen",
  hs: "hjelpestønad",
  ifm: "i forbindelse med",
  ifu: "inntekt før uførhet",
  ig: "inntektsgrense",
  iht: "i henhold til",
  ila: "i løpet av",
  im: "inntektsmelding",
  info: "informasjon",
  innk: "Innkrevingsmyndigheten",
  innst: "institusjonsopphold",
  io: "inntektsopplysninger",
  ip: "inntektsplanlegger",
  klp: "Kommunal Landspensjonskasse",
  krr: "kontakt- og reservasjonsregisteret",
  ks: "kontantstøtte",
  ksen: "Cash-for-Care benefit",
  kto: "kontonummer",
  laj: "levealdersjustering",
  lge: "legeerklæring",
  lvt: "leveattest",
  mk: "meldekort",
  mken: "employment status form",
  mld: "melding",
  mnd: "måned",
  mpn: "minste pensjonsnivå",
  mvh: "Med vennlig hilsen",
  mvhen: "Kind regards",
  mvhnn: "Med venleg helsing",
  navk: "Nav klageinstans",
  nay: "Nav arbeid og ytelser",
  nfp: "Nav familie- og pensjonsytelser",
  nks: "Nav kontaktsenter",
  nma: "Nav medlemskap og avgift",
  nøp: "Nav økonomi pensjon",
  nøs: "Nav økonomi stønad",
  od: "omsorgsdager",
  ogs: "overgangsstønad",
  ogsen: "transitional benefit",
  omst: "omstillingsstønad",
  oo: "omsorgsopptjening",
  op: "omsorgspenger",
  oppl: "opplysninger",
  oppp: "opplæringspenger",
  pber: "pensjonsberegning",
  pga: "på grunn av",
  pgi: "pensjonsgivende inntekt",
  pkalk: "pensjonskalkulator",
  pl: "pleiepenger",
  plis: "pleiepenger i livets sluttfase",
  plnæ: "pleiepenger nærstående",
  plsb: "pleiepenger sykt barn",
  pri: "prioritering",
  pv: "permitteringsvarsel",
  reg: "registrere",
  regas: "registrere deg som arbeidssøker",
  regu: "regulering",
  rol: "rådgivende overlege",
  sb: "saksbehandler",
  sbi: "særbidrag",
  sbt: "saksbehandlingstid",
  sbten: "processing time",
  sif: "sykdom i familien",
  sis: "Statens Innkrevingssentral",
  sit: "situasjon",
  ska: "Skatteetaten",
  skb: "skilsmissebevilling",
  slbg: "sletting av bidragsgjeld",
  sm: "sykmelding",
  sn: "selvstendig næringsdrivende",
  snr: "saksnummer",
  sobaor: "søknad om ordinær barnetrygd",
  sobaut: "søknad om utvidet barnetrygd",
  sobb: "søknad om barnebidrag",
  sobf: "søknad om bidragsforskudd",
  sodp: "søknad om dagpenger",
  sodpen: "application for unemployment benefits",
  soebb: "søknad om endring av barnebidrag",
  soes: "søknad om engangsstønad",
  sofp: "søknad om foreldrepenger",
  soks: "søknad om kontantstøtte",
  soos: "søknad om overgangsstønad",
  sopl: "søknad om pleiepenger",
  sosbg: "søknad om sletting av bidragsgjeld",
  sosbi: "søknad om særbidrag",
  sosp: "søknad om sykepenger",
  sospen: "application for sickness benefits",
  sostb: "søknad om stønad til barnetilsyn",
  sosvp: "søknad om svangerskapspenger",
  sots: "søknad om tilleggsstønad",
  soaap: "søknad om arbeidsavklaringspenger",
  sp: "sykepenger",
  spen: "sickness benefits",
  spk: "Statens pensjonskasse",
  spm: "spørsmål",
  ss: "søknadsskjema",
  stb: "stønad til barnetilsyn",
  sto: "Skriv til oss",
  su: "supplerende stønad",
  svp: "svangerskapspenger",
  svpen: "pregnancy benefit",
  tb: "Teknisk brukerstøtte nav.no",
  tbm: "tilbakemelding",
  tiom: "til og med",
  tlf: "telefon",
  tp: "tjenestepensjon",
  tr: "trygderetten",
  ts: "tilleggsstønad",
  ub: "utbetaling",
  uf: "uføretrygd",
  ufen: "disability benefit",
  usm: "utenlandsk sykemelding",
  vd: "virkedager",
  vt: "vedtak",
  wbto: "nav.no/send-beskjed",
  weo: "nav.no/uføre-etteroppgjør",
  wferie: "nav.no/feriepenger",
  wip: "nav.no/inntektsplanleggeren",
  wkontakt: "nav.no/kontaktoss",
  wsbt: "nav.no/saksbehandlingstider",
  wsto: "nav.no/skriv-til-oss",
  wub: "nav.no/utbetalingsdatoer",
  yrk: "yrkesskade",
  ys: "yrkesskade",
  øksit: "økonomiske situasjon",
};

export function getAbbreviationSuggestion(text: string): { abbr: string; expansion: string } | null {
  const match = text.match(/(?:^|\s)([a-zA-Z0-9øæåØÆÅ][a-zA-Z0-9øæåØÆÅ-]*)$/)
  if (!match) return null
  const word = match[1].toLowerCase()
  if (ABBREVIATIONS[word]) {
    return { abbr: word, expansion: ABBREVIATIONS[word] }
  }
  return null
}

const TRIGGERS = new Set([" ", ",", ".", "-", "!", "?"])

export function expandAbbreviationInText(text: string): string | null {
  if (text.length === 0) return null
  const lastChar = text[text.length - 1]
  if (!TRIGGERS.has(lastChar)) return null

  const beforeTrigger = text.slice(0, -1)
  const match = beforeTrigger.match(/(?:^|\s)([a-zA-Z0-9øæåØÆÅ][a-zA-Z0-9øæåØÆÅ-]*)$/)
  if (!match) return null

  const word = match[1].toLowerCase()
  if (!ABBREVIATIONS[word]) return null

  return beforeTrigger.slice(0, match.index! + (match[0].length - match[1].length)) + ABBREVIATIONS[word] + lastChar
}

export function expandAllAbbreviations(text: string): string {
  return text.replace(
    /([a-zA-Z0-9øæåØÆÅ][a-zA-Z0-9øæåØÆÅ-]*)(?=[\s,.\-!?]|$)/g,
    (match) => ABBREVIATIONS[match.toLowerCase()] ?? match,
  )
}