name: Deploy Bob frontend to prod

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Bygg
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@4219f2e6bfdb4cce482b78f71ad9663e64f4d247 # v2.0.0
        id: versions

      - name: Install pnpm ${{ steps.versions.outputs.pnpm }}
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: ${{ steps.versions.outputs.pnpm }}

      - name: Use Node.js ${{ steps.versions.outputs.nodejs }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}
          registry-url: 'https://npm.pkg.github.com'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - run: pnpm run --stream build

      - uses: nais/docker-build-push@8e41f1f58749b9248e376c25d33bfbdd2b1163c0 # v0
        id: gar-push
        with:
          team: nks-aiautomatisering
          salsa: true
          tag: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - id: upload
        uses: nais/deploy/actions/cdn-upload/v2@027a91857992525139798892f2804b0ca21f4af6 # v2
        with:
          team: nks-aiautomatisering
          source: ./dist/
          destination: '/'
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

    outputs:
      image: ${{ steps.gar-push.outputs.image }}
      digest: ${{ steps.gar-push.outputs.digest }}

  deploy-prod-gcp:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }},image=${{ needs.build.outputs.image }}
