name: Deploy NAIS poao-frontend to DEV
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/deploy-poao-frontend-dev.yaml'
      - .nais/nais-dev.yaml
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy poao-frontend to DEV
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
          PRINT_PAYLOAD: true
