name: Deploy NAIS nks-bob-frontend-server to DEV
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/deploy-nks-bob-frontend-server-dev.yaml"
      - .nais/dev-gcp.yaml
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/deploy-nks-bob-frontend-server-dev.yaml"
      - .nais/dev-gcp.yaml
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy nks-bob-frontend-server to DEV
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp.yaml
          PRINT_PAYLOAD: true
