name: Deploy Bob frontend to dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Bygg
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@4bd1f9ef2fe651f208080f38c698a3c5707dd1c1
        with:
          node-version-file: .node-version
          registry-url: https://npm.pkg.github.com
          scope: navikt
          cache: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - run: vp run build:frontend && vp run --filter server build

      - run: rm -rf node_modules server/node_modules && vp install --prod --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - uses: nais/docker-build-push@423a915c9b72edf2ba848b88171ccb0489e2a40a # v0
        id: gar-push
        with:
          team: nks-aiautomatisering
          salsa: true
          tag: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - id: upload
        uses: nais/deploy/actions/cdn-upload/v2@7ad7c2b833e1db74a80954e3ee6bb6ac060a8ae7 # v2
        with:
          team: nks-aiautomatisering
          source: ./dist/
          destination: "/"
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

    outputs:
      image: ${{ steps.gar-push.outputs.image }}
      digest: ${{ steps.gar-push.outputs.digest }}

  deploy-dev-gcp:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@7ad7c2b833e1db74a80954e3ee6bb6ac060a8ae7 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }},image=${{ needs.build.outputs.image }}
